# Generated by Django 4.2.3 on 2023-10-23 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profesor',
            name='telefono',
        ),
        migrations.AddField(
            model_name='profesor',
            name='phone_code',
            field=models.IntegerField(default=0, max_length=3, verbose_name='Código de Teléfono'),
        ),
        migrations.AddField(
            model_name='profesor',
            name='phone_number',
            field=models.IntegerField(default=0, max_length=15, verbose_name='Número de Teléfono'),
        ),
    ]
