# Generated by Django 4.2.6 on 2023-10-31 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesor', '0005_profesor_biografia_alter_profesor_phone_code_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profesor',
            options={'verbose_name': 'Profesor', 'verbose_name_plural': 'Profesores'},
        ),
        migrations.AddField(
            model_name='profesor',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='profesores'),
        ),
        migrations.AddField(
            model_name='profesor',
            name='materia',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profesor',
            name='precio',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='biografia',
            field=models.TextField(null=True),
        ),
    ]
