# Generated by Django 4.2.6 on 2023-10-31 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesor', '0006_alter_profesor_options_profesor_foto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesor',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='media/profesores'),
        ),
    ]
