# Generated by Django 4.2.6 on 2023-10-23 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumno', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='phone_code',
        ),
        migrations.AddField(
            model_name='alumno',
            name='code',
            field=models.IntegerField(default=0, max_length=3, verbose_name='código'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='phone_number',
            field=models.IntegerField(default=0, max_length=15, verbose_name='Número de Teléfono'),
        ),
    ]
