# Generated by Django 4.2.6 on 2023-10-23 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumno', '0002_remove_alumno_phone_code_alumno_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='code',
            field=models.IntegerField(default=0, max_length=3, verbose_name='código'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='phone_number',
            field=models.IntegerField(default=0, max_length=15, verbose_name='Número de Teléfono'),
        ),
    ]
