# Generated by Django 4.2.6 on 2023-10-25 01:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumno', '0004_remove_alumno_code_alumno_phone_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='phone_code',
            field=models.IntegerField(default=10, validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(10)], verbose_name='Código de Teléfono'),
        ),
    ]
