# Generated by Django 4.2.7 on 2023-11-02 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumno', '0006_alumno_num_documento_alumno_tipo_documento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='phone_code',
        ),
    ]
