# Generated by Django 4.2.7 on 2023-11-02 23:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumno', '0007_remove_alumno_phone_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='num_documento',
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='tipo_documento',
        ),
        migrations.AddField(
            model_name='alumno',
            name='phone_code',
            field=models.IntegerField(default=10, validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(10)], verbose_name='Código de Teléfono'),
        ),
    ]
