# Generated by Django 4.2.7 on 2023-11-02 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumno', '0008_remove_alumno_num_documento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='num_documento',
            field=models.CharField(default='', max_length=100, verbose_name='Nro. Documento'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='tipo_documento',
            field=models.CharField(default='', max_length=100, verbose_name='Tipo de Documento'),
        ),
    ]
