# Generated by Django 4.2.6 on 2023-10-29 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aula_virtual', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aulavirtual',
            name='nombre',
            field=models.CharField(default=2, max_length=50, verbose_name='nombre'),
            preserve_default=False,
        ),
    ]
