# Generated by Django 4.2.6 on 2023-10-29 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aula_virtual', '0002_aulavirtual_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aulavirtual',
            name='fecha',
            field=models.DateField(verbose_name='fecha_de_clase'),
        ),
    ]
